import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Advertise from "../components/LandingPage/Advertise";

import FeaturesSec from "../components/LandingPage/FeaturesSec";
import FeaturesSec2 from "../components/LandingPage/FeaturesSec2";
import Hero from "../components/LandingPage/Hero";
import TeamLanding from "../components/LandingPage/TeamLanding";
import VideoSection from "../components/LandingPage/VideoSection";
import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />

        <VideoSection />
        <FeaturesSec />
        <FeaturesSec2 />
        <TeamLanding />
        <Advertise />
      </Layout>
    </div>
  );
}
